## 
##
##
# 默认服务器编号为0
server_index: 0
secret_key: 00112233445566778899AABBCCDDEEFF
# 默认启用JWT认证，此处默认：不开启
database_auth_enabled: true
# 这个是有效期，默认为24小时，这里是秒为单位
database_auth_expired: 86400
# JWT 
jwt_enabled: true
# 只有开启JWT认证，才会启用认证
jwt_auth_enabled: true
# 该密钥为开发密钥，请不要用于生产，切记
jwt_secret_key: ”kmd77171cbkqSu1c“
# 这个是有效期，默认为24小时，这里是秒为单位
jwt_expired: 86400
room:
  room_max: 1000
  # 一个房间最大的玩家数，包括AI及其它
  players_max: 2
  # 目前没有参观游戏的玩家
  lookon_max: 0
match_server: 
  # AI玩家,开启该项，仅仅匹配AI，不匹配玩家
  ai_player_enabled: true
  # 最大AI数量，小于这个数量AI只会创建
  ai_player_max: 1000
  # AI是否唯一性，一个基础AI可以衍生多个同名AI
  # 配置false，需要配置表中有对应数量
  ai_player_derived: true
  # 最大处理数量
  poll_max: 100
server:
  address: "0.0.0.0"
  port: 5900
  ssl: true
  ssl_certs: "certs/wss.crt"
  ssl_key: "certs/wss.pem"
http_server:
 - address: "0.0.0.0"
   port: 5000
 - address: "0.0.0.0"
   port: 5443
   ssl: true
   ssl_certs: "certs/https.crt"
   ssl_key: "certs/https.pem.unsecure"
# internal server
 - address: "0.0.0.0"
   port: 9443
   internal: true
   ssl: true
   ssl_certs: "certs/https.crt"
   ssl_key: "certs/https.pem.unsecure"
   allow_address_list:
    - "127.0.0.1"
    - "10.182.207.169" #开发测试
    - "10.182.207.180" #开发测试
playfab:
  openapi_url: "https://127.0.0.1:15443"
  openapi_key: "C465B2315CF4A31ECA4F912D2723E08E0C8A84941DCCF4846B9E642366ADF1F03A2F650305324645F5060630A8FDB454"
database:
   # 主数据库
   - type: main
     name: game
     user: service
     pass: "game123..."
     address: "127.0.0.1"
     port: 3306
     # SSL 默认:开启
     ssl: true
     ssl_certs: "certs/db.crt"
     ssl_key: "certs/db_rsa_2048.pem.unsecure"
redis:
  # 主数据库
  name: "master-server"
  user: service
  pass: "game123..."
  address: "10.182.207.180"
  port: 6379
  # SSL 默认:开启
  ssl: true
  ssl_certs: "certs/redis.crt"
  ssl_key: "certs/redis_rsa_2048.pem.unsecure"
logging:
  # 默认服务日志
  - name: main
    level: Information
    file: "logs/main.log"
  # HTTP 服务日志
  - name: http
    level: Information
    file: "logs/http.log"
  # PlayFab 第三方代理服务
  - name: redis
    level: Information
    file: "logs/redis.log"
    is_file: true
    is_console: true
  # 数据库日志
  - name: database
    level: Information
    file: "logs/database.log"
  # 数据库sql查询日志
  - name: database_query
    level: Information
    file: "logs/database_query.log"
    is_file: true
    is_console: false
  # 匹配数量多，不建议使用默认等级
  - name: game_match
    level: Error
    file: "logs/game_match.log"
    is_file: true
    is_console: true
  # 房间使用日志
  - name: room
    level: Information
    file: "logs/room.log"
    is_file: true
    is_console: true
  # 支付日志
  - name: payment
    level: Information
    file: "logs/payment.log"
    is_file: true
    is_console: false
  # PlayFab 第三方代理服务
  - name: playfab
    level: Information
    file: "logs/playfab.log"
    is_file: true
    is_console: false
    