## 
##
##
secret_key: 00112233445566778899AABBCCDDEEFF
# 默认启用JWT认证，此处默认：不开启
database_auth_enabled: true
# 这个是有效期，默认为24小时，这里是秒为单位
database_auth_expired: 86400
# JWT 
jwt_enabled: true
# 只有开启JWT认证，才会启用认证
jwt_auth_enabled: true
# 该密钥为开发密钥，请不要用于生产，切记
jwt_secret_key: ”kmd77171cbkqSu1c“
# 这个是有效期，默认为24小时，这里是秒为单位
jwt_expired: 86400
http_server:
 - address: "0.0.0.0"
   port: 5000
 - address: "0.0.0.0"
   port: 5443
   ssl: true
   certs: "certs/https.pfx"
database:
   # 主数据库
   - type: main
     name: game
     user: service
     pass: "game123..."
     address: "127.0.0.1"
     port: 3306
     # SSL 默认:开启
     ssl: true
     ssl_certs: "certs/db.crt"
     ssl_key: "certs/db_rsa_2048.pem.unsecure"
logging:
  # 默认服务日志
  - name: main
    level: Information
    file: "logs/main.log"
  # HTTP 服务日志
  - name: http
    level: Information
    file: "logs/http.log"
  # 数据库日志
  - name: database
    level: Information
    file: "logs/database.log"
  # 数据库sql查询日志
  - name: database_query
    level: Information
    file: "logs/database_query.log"
    is_file: true
    is_console: false
  # 匹配数量多，不建议使用默认等级
  - name: game_match
    level: Error
    file: "logs/game_match.log"
    is_file: true
    is_console: true
