secret_key: 00112233445566778899AABBCCDDEEFF
http_server:
 - address: "0.0.0.0"
   port: 5000
 - address: "0.0.0.0"
   port: 5443
   ssl: true
   certs: "certs/https.pfx"
logging:
  - name: main
    level: Information
    file: "logs/main.log"
  - name: http
    level: Information
    file: "logs/http.log"
